import { docHead, TAIL } from './html-utils.js';
import type { SeedDocument } from './types.js';
export const maintenance: SeedDocument = {
  title: '保守運用契約書',
  description: 'システム保守運用業務の契約書',
  sections: [
    { title: '表紙', html: docHead('<style>body{background:linear-gradient(135deg,#134e4a 0%,#0f766e 100%);color:#fff}</style>') + `<div class="w-[1920px] h-[1080px] flex flex-col items-center justify-center"><div class="text-7xl font-black mb-6">保守運用契約書</div><div class="w-32 h-1 bg-white/30 mb-8"></div><div class="text-xl opacity-70">System Maintenance Agreement</div></div>` + TAIL },
    { title: '保守範囲・SLA', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-3xl font-bold text-slate-800 mb-8">第1条 保守範囲およびSLA</div><div class="space-y-6"><div class="border-l-4 border-red-500 bg-red-50 rounded-r-xl p-6"><div class="font-bold text-red-800 mb-2">P1: 致命的障害</div><div class="text-slate-700 text-sm">システム停止・全ユーザー影響 / 対応時間: 1時間以内 / 復旧目標: 4時間以内</div></div><div class="border-l-4 border-orange-500 bg-orange-50 rounded-r-xl p-6"><div class="font-bold text-orange-800 mb-2">P2: 重度障害</div><div class="text-slate-700 text-sm">主要機能不全・一部ユーザー影響 / 対応時間: 4時間以内 / 復旧目標: 8時間以内</div></div><div class="border-l-4 border-yellow-500 bg-yellow-50 rounded-r-xl p-6"><div class="font-bold text-yellow-800 mb-2">P3: 軽微障害</div><div class="text-slate-700 text-sm">代替手段あり・業務継続可能 / 対応時間: 翌営業日 / 復旧目標: 3営業日以内</div></div></div></div>` + TAIL },
    { title: '報酬・署名', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-3xl font-bold text-slate-800 mb-8">第2条 報酬 / 署名欄</div><div class="grid grid-cols-2 gap-6 mb-12"><div class="bg-teal-50 rounded-xl p-6"><div class="text-sm text-teal-600 mb-1">基本保守料(月額)</div><div class="text-2xl font-black text-teal-700">30万円</div><div class="text-sm text-slate-500 mt-1">監視・定期点検・軽微修正含む</div></div><div class="bg-teal-50 rounded-xl p-6"><div class="text-sm text-teal-600 mb-1">契約期間</div><div class="text-2xl font-black text-teal-700">1年間</div><div class="text-sm text-slate-500 mt-1">自動更新 / 30日前通告で解約可</div></div></div><div class="grid grid-cols-2 gap-16"><div class="border-2 border-slate-200 rounded-2xl p-6"><div class="font-bold mb-4">甲(委託者)</div><div class="text-sm space-y-2">商号: ___________________________<br>代表者: ___________________________<br>日付: 2026年 ___月 ___日</div></div><div class="border-2 border-slate-200 rounded-2xl p-6"><div class="font-bold mb-4">乙(保守提供者)</div><div class="text-sm space-y-2">商号: ___________________________<br>代表者: ___________________________<br>日付: 2026年 ___月 ___日</div></div></div></div>` + TAIL },
  ],
};
