import { docHead, TAIL } from './html-utils.js';
import type { SeedDocument } from './types.js';
export const nda: SeedDocument = {
  title: '秘密保持契約書 (NDA)',
  description: '双方向の秘密保持契約書',
  sections: [
    { title: '表紙', html: docHead('<style>body{background:linear-gradient(135deg,#334155 0%,#475569 100%);color:#fff}</style>') + `<div class="w-[1920px] h-[1080px] flex flex-col items-center justify-center"><div class="text-7xl font-black mb-6">秘密保持契約書</div><div class="w-32 h-1 bg-white/30 mb-8"></div><div class="text-xl opacity-70">Non-Disclosure Agreement</div></div>` + TAIL },
    { title: '目的・定義', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-3xl font-bold text-slate-800 mb-8">第1条 目的および秘密情報の定義</div><div class="text-slate-700 leading-8 space-y-4"><div>甲(開示者)と乙(受領者)は、〇〇プロジェクト(以下「本件」)に関する情報交換に際し、互いの秘密情報を保護するため、以下の通り契約する。</div><div class="bg-slate-50 rounded-xl p-6"><div class="font-bold mb-2">第1項 秘密情報とは</div><div>本契約に基づき開示される、技術情報、営業情報、顧客情報、財務情報、企画書、仕様書、ソースコード、その他一切の非公開情報をいう。</div></div><div class="bg-slate-50 rounded-xl p-6"><div class="font-bold mb-2">第2項 除外事項</div><div>既に公知の情報 / 開示時に既に保有していた情報 / 正当な権限を持つ第三者から合法的に取得した情報 / 法令により開示が求められる情報</div></div></div></div>` + TAIL },
    { title: '義務・期間', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-3xl font-bold text-slate-800 mb-8">第2条 守秘義務 / 第3条 有効期間</div><div class="text-slate-700 leading-8 space-y-4"><div class="bg-slate-50 rounded-xl p-6"><div class="font-bold mb-2">第2条 守秘義務</div><div>(1) 受領者は、開示者の書面による事前承諾なく、秘密情報を第三者に開示または漏洩してはならない。<br>(2) 受領者は、秘密情報を本件の目的以外に使用してはならない。<br>(3) 受領者は、秘密情報を必要最小限の範囲の従業員にのみ開示するものとし、当該従業員に対しても同等の守秘義務を負担させる。</div></div><div class="bg-slate-50 rounded-xl p-6"><div class="font-bold mb-2">第3条 有効期間</div><div>本契約は、締結日より3年間有効とする。但し、第2条の守秘義務は契約終了後も3年間存続する。</div></div></div></div>` + TAIL },
    { title: '署名欄', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-3xl font-bold text-slate-800 mb-8">署名欄</div><div class="text-slate-600 mb-12">上記の通り契約が成立したことを証するため、本書2通を作成し、各1通を保有する。</div><div class="grid grid-cols-2 gap-16"><div class="border-2 border-slate-200 rounded-2xl p-8"><div class="text-lg font-bold text-slate-800 mb-6">甲(開示者)</div><div class="space-y-4 text-sm"><div>商号: ___________________________</div><div>所在地: ___________________________</div><div>代表者名: ___________________________</div><div class="mt-6 pt-6 border-t border-slate-200"><div class="text-slate-500 mb-1">捨印</div><div class="h-20 border border-dashed border-slate-300 rounded"></div></div><div class="mt-4">日付: 2026年 ___月 ___日</div></div></div><div class="border-2 border-slate-200 rounded-2xl p-8"><div class="text-lg font-bold text-slate-800 mb-6">乙(受領者)</div><div class="space-y-4 text-sm"><div>商号: ___________________________</div><div>所在地: ___________________________</div><div>代表者名: ___________________________</div><div class="mt-6 pt-6 border-t border-slate-200"><div class="text-slate-500 mb-1">捨印</div><div class="h-20 border border-dashed border-slate-300 rounded"></div></div><div class="mt-4">日付: 2026年 ___月 ___日</div></div></div></div></div>` + TAIL },
  ],
};
