import { docHead, TAIL } from './html-utils.js';
import type { SeedDocument } from './types.js';
export const outsourcing: SeedDocument = {
  title: '業務委託契約書',
  description: 'システム開発業務委託契約書',
  sections: [
    { title: '表紙', html: docHead('<style>body{background:linear-gradient(135deg,#312e81 0%,#4338ca 100%);color:#fff}</style>') + `<div class="w-[1920px] h-[1080px] flex flex-col items-center justify-center"><div class="text-7xl font-black mb-6">業務委託契約書</div><div class="w-32 h-1 bg-white/30 mb-8"></div><div class="text-xl opacity-70">System Development Outsourcing Agreement</div></div>` + TAIL },
    { title: '委託内容', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-3xl font-bold text-slate-800 mb-8">第1条 委託業務内容</div><div class="text-slate-700 leading-8 space-y-4"><div>甲は乙に対し、以下のシステム開発業務を委託する。</div><div class="bg-indigo-50 rounded-xl p-6"><table class="w-full"><tbody class="text-slate-700"><tr class="border-b border-indigo-100"><td class="py-3 text-slate-500 w-40">プロジェクト名</td><td class="py-3 font-semibold">〇〇統合業務システム開発</td></tr><tr class="border-b border-indigo-100"><td class="py-3 text-slate-500">委託範囲</td><td class="py-3">要件定義・設計・開発・テスト・本番移行</td></tr><tr class="border-b border-indigo-100"><td class="py-3 text-slate-500">委託期間</td><td class="py-3">2026年5月1日〜2026年12月31日</td></tr><tr><td class="py-3 text-slate-500">納品物</td><td class="py-3">ソースコード・設計書・テスト結果報告書・運用マニュアル</td></tr></tbody></table></div></div></div>` + TAIL },
    { title: '報酬・マイルストーン', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-3xl font-bold text-slate-800 mb-8">第2条 報酬および支払条件</div><div class="mb-8"><table class="w-full"><thead><tr class="border-b-2 border-slate-200"><th class="py-3 text-left text-sm text-slate-500">マイルストーン</th><th class="py-3 text-left text-sm text-slate-500">内容</th><th class="py-3 text-sm text-slate-500">期限</th><th class="py-3 text-right text-sm text-slate-500">報酬</th></tr></thead><tbody class="text-slate-800"><tr class="border-b border-slate-100"><td class="py-4 font-semibold">M1: 要件定義完了</td><td class="py-4">要件定義書承認</td><td class="py-4">6月末</td><td class="py-4 text-right font-mono">200万円</td></tr><tr class="border-b border-slate-100"><td class="py-4 font-semibold">M2: 設計完了</td><td class="py-4">基本・詳細設計書承認</td><td class="py-4">8月末</td><td class="py-4 text-right font-mono">300万円</td></tr><tr class="border-b border-slate-100"><td class="py-4 font-semibold">M3: 開発完了</td><td class="py-4">結合テスト完了</td><td class="py-4">11月末</td><td class="py-4 text-right font-mono">500万円</td></tr><tr class="border-b border-slate-100"><td class="py-4 font-semibold">M4: 本番稼働</td><td class="py-4">本番移行・検収完了</td><td class="py-4">12月末</td><td class="py-4 text-right font-mono">200万円</td></tr></tbody></table></div><div class="bg-indigo-50 rounded-xl p-4 flex justify-between items-center"><span class="text-slate-600">委託報酬総額</span><span class="text-2xl font-black text-indigo-700">1,200万円(税抜)</span></div></div>` + TAIL },
    { title: '秘密保持・署名', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-3xl font-bold text-slate-800 mb-8">第3条 秘密保持 / 署名欄</div><div class="bg-slate-50 rounded-xl p-6 mb-10 text-slate-700 leading-7"><div class="font-bold mb-2">秘密保持</div><div>乙は、業務の遂行により知り得た甲の秘密情報を、第三者に開示または漏洩してはならない。本義務は契約終了後3年間有効とする。</div></div><div class="grid grid-cols-2 gap-16"><div class="border-2 border-slate-200 rounded-2xl p-8"><div class="text-lg font-bold mb-6">甲(委託者)</div><div class="space-y-3 text-sm"><div>商号: ___________________________</div><div>代表者: ___________________________</div><div>日付: 2026年 ___月 ___日</div><div class="mt-4 h-16 border border-dashed border-slate-300 rounded"></div></div></div><div class="border-2 border-slate-200 rounded-2xl p-8"><div class="text-lg font-bold mb-6">乙(受託者)</div><div class="space-y-3 text-sm"><div>商号: ___________________________</div><div>代表者: ___________________________</div><div>日付: 2026年 ___月 ___日</div><div class="mt-4 h-16 border border-dashed border-slate-300 rounded"></div></div></div></div></div>` + TAIL },
  ],
};
