import { docHead, TAIL } from './html-utils.js';
import type { SeedDocument } from './types.js';
export const progressReport: SeedDocument = {
  title: '進捗報告書',
  description: 'プロジェクト進捗の定期報告書',
  sections: [
    { title: '表紙・サマリー', html: docHead('<style>body{background:linear-gradient(135deg,#14532d 0%,#166534 100%);color:#fff}</style>') + `<div class="w-[1920px] h-[1080px] flex flex-col items-center justify-center"><div class="text-7xl font-black mb-6">進捗報告書</div><div class="w-32 h-1 bg-white/30 mb-8"></div><div class="text-2xl opacity-80">〇〇システム開発プロジェクト</div><div class="text-lg opacity-60 mt-2">2026年7月度 月次報告</div></div>` + TAIL },
    { title: '進捗状況', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">進捗状況</div><div class="grid grid-cols-4 gap-4 mb-10"><div class="bg-emerald-50 rounded-xl p-6 text-center"><div class="text-sm text-emerald-600 mb-1">全体進捗</div><div class="text-3xl font-black text-emerald-700">62%</div></div><div class="bg-green-50 rounded-xl p-6 text-center"><div class="text-sm text-green-600 mb-1">SPI</div><div class="text-3xl font-black text-green-700">1.05</div></div><div class="bg-amber-50 rounded-xl p-6 text-center"><div class="text-sm text-amber-600 mb-1">CPI</div><div class="text-3xl font-black text-amber-700">0.95</div></div><div class="bg-blue-50 rounded-xl p-6 text-center"><div class="text-sm text-blue-600 mb-1">残作業</div><div class="text-3xl font-black text-blue-700">38%</div></div></div><div class="space-y-3"><div class="flex items-center gap-4"><div class="w-32 font-semibold text-slate-700">要件定義</div><div class="flex-1 bg-slate-100 rounded-full h-6"><div class="bg-emerald-500 h-6 rounded-full" style="width:100%"></div></div><div class="w-12 text-right text-sm text-emerald-600 font-bold">100%</div></div><div class="flex items-center gap-4"><div class="w-32 font-semibold text-slate-700">基本設計</div><div class="flex-1 bg-slate-100 rounded-full h-6"><div class="bg-emerald-500 h-6 rounded-full" style="width:100%"></div></div><div class="w-12 text-right text-sm text-emerald-600 font-bold">100%</div></div><div class="flex items-center gap-4"><div class="w-32 font-semibold text-slate-700">実装</div><div class="flex-1 bg-slate-100 rounded-full h-6"><div class="bg-blue-500 h-6 rounded-full" style="width:45%"></div></div><div class="w-12 text-right text-sm text-blue-600 font-bold">45%</div></div><div class="flex items-center gap-4"><div class="w-32 font-semibold text-slate-700">テスト</div><div class="flex-1 bg-slate-100 rounded-full h-6"><div class="bg-slate-300 h-6 rounded-full" style="width:0%"></div></div><div class="w-12 text-right text-sm text-slate-400 font-bold">0%</div></div></div></div>` + TAIL },
    { title: '課題・リスク', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">課題・リスク</div><div class="space-y-4"><div class="bg-red-50 rounded-xl p-6 border-l-4 border-red-500"><div class="flex justify-between"><div class="font-bold text-red-800">API仕様の未確定</div><span class="bg-red-200 text-red-800 px-2 py-0.5 rounded text-xs font-bold">要対応</span></div><div class="text-sm text-slate-600 mt-2">外部システム連携APIの仕様が未確定。来週までに確定予定。影響: 実装2週間遅延の可能性。</div></div><div class="bg-amber-50 rounded-xl p-6 border-l-4 border-amber-500"><div class="flex justify-between"><div class="font-bold text-amber-800">パフォーマンス懸念</div><span class="bg-amber-200 text-amber-800 px-2 py-0.5 rounded text-xs font-bold">注視</span></div><div class="text-sm text-slate-600 mt-2">一覧画面の初期表示が目標3秒に対し現在4.5秒。DBインデックス最適化で改善予定。</div></div><div class="bg-green-50 rounded-xl p-6 border-l-4 border-green-500"><div class="flex justify-between"><div class="font-bold text-green-800">メンバー追加</div><span class="bg-green-200 text-green-800 px-2 py-0.5 rounded text-xs font-bold">解決済</span></div><div class="text-sm text-slate-600 mt-2">フロントエンド担当1名追加(8月〜)。リソース不足リスクは解消。</div></div></div></div>` + TAIL },
    { title: '今後の予定', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">今後の予定</div><div class="space-y-4"><div class="flex items-center gap-6"><div class="w-24 text-right font-bold text-slate-600">8月</div><div class="flex-1 bg-blue-50 rounded-xl p-4"><div class="font-bold text-blue-800">実装完了</div><div class="text-sm text-slate-600">全モジュール実装完了・コードレビュー</div></div></div><div class="flex items-center gap-6"><div class="w-24 text-right font-bold text-slate-600">9月</div><div class="flex-1 bg-indigo-50 rounded-xl p-4"><div class="font-bold text-indigo-800">テストフェーズ</div><div class="text-sm text-slate-600">単体テスト・結合テスト・性能テスト</div></div></div><div class="flex items-center gap-6"><div class="w-24 text-right font-bold text-slate-600">10月</div><div class="flex-1 bg-purple-50 rounded-xl p-4"><div class="font-bold text-purple-800">総合テスト</div><div class="text-sm text-slate-600">ユーザー受け入れテスト・本番環境構築</div></div></div><div class="flex items-center gap-6"><div class="w-24 text-right font-bold text-slate-600">11月</div><div class="flex-1 bg-emerald-50 rounded-xl p-4"><div class="font-bold text-emerald-800">本番移行</div><div class="text-sm text-slate-600">データ移行・並行運用・検収</div></div></div></div></div>` + TAIL },
  ],
};
