import { docHead, TAIL } from './html-utils.js';
import type { SeedDocument } from './types.js';
export const projectPlan: SeedDocument = {
  title: 'プロジェクト計画書',
  description: 'プロジェクトの全体計画書',
  sections: [
    { title: '表紙', html: docHead('<style>body{background:linear-gradient(135deg,#1e40af 0%,#2563eb 100%);color:#fff}</style>') + `<div class="w-[1920px] h-[1080px] flex flex-col items-center justify-center"><div class="text-7xl font-black mb-6">プロジェクト計画書</div><div class="w-32 h-1 bg-white/30 mb-8"></div><div class="text-2xl opacity-80">〇〇システム開発プロジェクト</div></div>` + TAIL },
    { title: 'プロジェクト概要', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">プロジェクト概要</div><div class="grid grid-cols-2 gap-8"><div class="bg-blue-50 rounded-2xl p-8"><div class="text-sm text-blue-600 mb-1">プロジェクト名</div><div class="text-xl font-bold">〇〇統合業務システム開発</div></div><div class="bg-blue-50 rounded-2xl p-8"><div class="text-sm text-blue-600 mb-1">期間</div><div class="text-xl font-bold">2026年5月〜12月(8ヶ月)</div></div><div class="bg-blue-50 rounded-2xl p-8"><div class="text-sm text-blue-600 mb-1">予算</div><div class="text-xl font-bold">1,200万円</div></div><div class="bg-blue-50 rounded-2xl p-8"><div class="text-sm text-blue-600 mb-1">プロジェクトマネージャー</div><div class="text-xl font-bold">山田 太郎</div></div></div></div>` + TAIL },
    { title: 'WBS', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">WBS(作業分解構成)</div><table class="w-full text-sm"><thead><tr class="border-b-2 border-slate-200"><th class="py-3 text-left text-slate-500">WBS</th><th class="py-3 text-left text-slate-500">作業内容</th><th class="py-3 text-slate-500">担当</th><th class="py-3 text-slate-500">5月</th><th class="py-3 text-slate-500">6月</th><th class="py-3 text-slate-500">7月</th><th class="py-3 text-slate-500">8月</th><th class="py-3 text-slate-500">9-10月</th><th class="py-3 text-slate-500">11-12月</th></tr></thead><tbody class="text-slate-700"><tr class="border-b border-slate-100"><td class="py-3 font-semibold">1. 要件定義</td><td class="py-3">業務ヒアリング・要件整理</td><td class="py-3">PM+SE</td><td class="py-3 text-center bg-blue-100">●</td><td class="py-3 text-center bg-blue-100">●</td><td class="py-3"></td><td class="py-3"></td><td class="py-3"></td><td class="py-3"></td></tr><tr class="border-b border-slate-100"><td class="py-3 font-semibold">2. 基本設計</td><td class="py-3">アーキテクチャ・DB・API設計</td><td class="py-3">SE</td><td class="py-3"></td><td class="py-3 text-center bg-blue-100">●</td><td class="py-3 text-center bg-blue-100">●</td><td class="py-3"></td><td class="py-3"></td><td class="py-3"></td></tr><tr class="border-b border-slate-100"><td class="py-3 font-semibold">3. 実装</td><td class="py-3">フロントエンド・バックエンド開発</td><td class="py-3">SE×3</td><td class="py-3"></td><td class="py-3"></td><td class="py-3 text-center bg-blue-100">●</td><td class="py-3 text-center bg-blue-100">●</td><td class="py-3 text-center bg-blue-100">●</td><td class="py-3"></td></tr><tr class="border-b border-slate-100"><td class="py-3 font-semibold">4. テスト</td><td class="py-3">単体・結合・総合テスト</td><td class="py-3">SE+QA</td><td class="py-3"></td><td class="py-3"></td><td class="py-3"></td><td class="py-3"></td><td class="py-3 text-center bg-blue-100">●</td><td class="py-3 text-center bg-blue-100">●</td></tr><tr><td class="py-3 font-semibold">5. 本番移行</td><td class="py-3">データ移行・検収・教育</td><td class="py-3">PM+SE</td><td class="py-3"></td><td class="py-3"></td><td class="py-3"></td><td class="py-3"></td><td class="py-3"></td><td class="py-3 text-center bg-blue-100">●</td></tr></tbody></table></div>` + TAIL },
    { title: 'リスク管理', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">リスク管理</div><table class="w-full"><thead><tr class="border-b-2 border-slate-200"><th class="py-3 text-left text-sm text-slate-500">リスク</th><th class="py-3 text-sm text-slate-500">影響度</th><th class="py-3 text-sm text-slate-500">確率</th><th class="py-3 text-sm text-slate-500">対策</th></tr></thead><tbody class="text-slate-700"><tr class="border-b border-slate-100"><td class="py-4">要件変更の頻発</td><td class="py-4"><span class="bg-red-100 text-red-700 px-2 py-1 rounded text-sm font-semibold">高</span></td><td class="py-4"><span class="bg-amber-100 text-amber-700 px-2 py-1 rounded text-sm font-semibold">中</span></td><td class="py-4">変更管理プロセスの導入・影響分析の必須化</td></tr><tr class="border-b border-slate-100"><td class="py-4">要員の離脱</td><td class="py-4"><span class="bg-red-100 text-red-700 px-2 py-1 rounded text-sm font-semibold">高</span></td><td class="py-4"><span class="bg-green-100 text-green-700 px-2 py-1 rounded text-sm font-semibold">低</span></td><td class="py-4">ペアプログラミング・ナレッジ共有の徹底</td></tr><tr class="border-b border-slate-100"><td class="py-4">スケジュール遅延</td><td class="py-4"><span class="bg-amber-100 text-amber-700 px-2 py-1 rounded text-sm font-semibold">中</span></td><td class="py-4"><span class="bg-amber-100 text-amber-700 px-2 py-1 rounded text-sm font-semibold">中</span></td><td class="py-4">バッファ20%設定・週次進捗確認</td></tr></tbody></table></div>` + TAIL },
  ],
};
