import { docHead, TAIL } from './html-utils.js';
import type { SeedDocument } from './types.js';
export const quotation: SeedDocument = {
  title: '見積書',
  description: 'システム開発・導入の正式見積書',
  sections: [
    { title: '表紙', html: docHead('<style>body{background:linear-gradient(135deg,#065f46 0%,#047857 100%);color:#fff}</style>') + `<div class="w-[1920px] h-[1080px] flex flex-col items-center justify-center"><div class="text-7xl font-black mb-6">御 見 積 書</div><div class="w-32 h-1 bg-white/40 mb-8"></div><div class="text-2xl font-light opacity-80">〇〇株式会社 様</div><div class="mt-4 text-lg opacity-60">2026年4月9日</div></div>` + TAIL },
    { title: '見積明細', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="flex justify-between items-start mb-10"><div><div class="text-4xl font-bold text-slate-800">御見積書</div><div class="text-slate-500 mt-1">見積番号: QT-2026-0423</div></div><div class="text-right text-sm text-slate-500"><div>株式会社テクノバーン</div><div>〒150-0001 東京都渋谷区神宮前5-10-1</div></div></div><table class="w-full text-left"><thead><tr class="border-b-2 border-slate-800"><th class="py-3 text-sm text-slate-500">No.</th><th class="py-3 text-sm text-slate-500">項目</th><th class="py-3 text-sm text-slate-500">仕様・内容</th><th class="py-3 text-sm text-slate-500 text-right">数量</th><th class="py-3 text-sm text-slate-500 text-right">単価</th><th class="py-3 text-sm text-slate-500 text-right">金額</th></tr></thead><tbody class="text-slate-800"><tr class="border-b border-slate-100"><td class="py-4">1</td><td class="py-4 font-semibold">要件定義</td><td class="py-4">業務ヒアリング・要件整理</td><td class="py-4 text-right">1式</td><td class="py-4 text-right font-mono">100万</td><td class="py-4 text-right font-mono">100万円</td></tr><tr class="border-b border-slate-100"><td class="py-4">2</td><td class="py-4 font-semibold">基本設計</td><td class="py-4">システム基本設計書作成</td><td class="py-4 text-right">1式</td><td class="py-4 text-right font-mono">150万</td><td class="py-4 text-right font-mono">150万円</td></tr><tr class="border-b border-slate-100"><td class="py-4">3</td><td class="py-4 font-semibold">開発</td><td class="py-4">バックエンド+フロントエンド</td><td class="py-4 text-right">1式</td><td class="py-4 text-right font-mono">400万</td><td class="py-4 text-right font-mono">400万円</td></tr><tr class="border-b border-slate-100"><td class="py-4">4</td><td class="py-4 font-semibold">テスト</td><td class="py-4">単体・結合・総合テスト</td><td class="py-4 text-right">1式</td><td class="py-4 text-right font-mono">80万</td><td class="py-4 text-right font-mono">80万円</td></tr><tr class="border-b border-slate-100"><td class="py-4">5</td><td class="py-4 font-semibold">保守運用(1年)</td><td class="py-4">監視・障害対応・バグ修正</td><td class="py-4 text-right">12月</td><td class="py-4 text-right font-mono">15万</td><td class="py-4 text-right font-mono">180万円</td></tr></tbody></table><div class="mt-8 flex justify-end"><div class="w-80"><div class="flex justify-between py-2 border-b"><span class="text-slate-600">小計</span><span class="font-mono">910万円</span></div><div class="flex justify-between py-2 border-b"><span class="text-slate-600">消費税(10%)</span><span class="font-mono">91万円</span></div><div class="flex justify-between py-3 bg-emerald-50 rounded px-3 mt-2"><span class="font-bold text-emerald-800">合計</span><span class="text-2xl font-black text-emerald-700">1,001万円</span></div></div></div></div>` + TAIL },
    { title: '条件', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">見積条件</div><div class="space-y-4 text-slate-700"><div class="bg-slate-50 rounded-xl p-6"><div class="font-bold text-slate-800 mb-2">有効期限</div><div>本見積の有効期限は発行日より30日間とさせていただきます。</div></div><div class="bg-slate-50 rounded-xl p-6"><div class="font-bold text-slate-800 mb-2">支払条件</div><div>着手金30% / 中間精算30% / 納品時40%</div></div><div class="bg-slate-50 rounded-xl p-6"><div class="font-bold text-slate-800 mb-2">納期</div><div>ご発注より6ヶ月以内(別途スケジュール協定)</div></div><div class="bg-slate-50 rounded-xl p-6"><div class="font-bold text-slate-800 mb-2">保守期間</div><div>納品後1年間無償保守(バグ修正のみ)。以降は別途保守契約。</div></div></div></div>` + TAIL },
  ],
};
