import { docHead, TAIL } from './html-utils.js';
import type { SeedDocument } from './types.js';
export const requirements: SeedDocument = {
  title: '要件定義書',
  description: 'システム要件定義書',
  sections: [
    { title: '表紙', html: docHead('<style>body{background:linear-gradient(135deg,#312e81 0%,#4f46e5 100%);color:#fff}</style>') + `<div class="w-[1920px] h-[1080px] flex flex-col items-center justify-center"><div class="text-7xl font-black mb-6">要件定義書</div><div class="w-32 h-1 bg-white/30 mb-8"></div><div class="text-2xl opacity-80">〇〇統合業務システム</div></div>` + TAIL },
    { title: 'システム概要', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">システム概要</div><div class="grid grid-cols-2 gap-8 mb-8"><div class="bg-indigo-50 rounded-2xl p-8"><div class="text-sm text-indigo-600 mb-1">目的</div><div class="text-lg font-bold">全社業務プロセスのデジタル化とデータ統合による業務効率化</div></div><div class="bg-indigo-50 rounded-2xl p-8"><div class="text-sm text-indigo-600 mb-1">対象範囲</div><div class="text-lg font-bold">営業管理・顧客管理・経理業務・レポート機能</div></div></div><div class="bg-slate-50 rounded-2xl p-8"><div class="text-sm text-slate-500 mb-2">前提条件</div><div class="text-slate-700">・既存基幹システム(DB: Oracle)との連携必須 ・社員200名が利用 ・クラウド(AWS)前提</div></div></div>` + TAIL },
    { title: '機能要件', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">機能要件</div><table class="w-full text-sm"><thead><tr class="border-b-2 border-slate-200"><th class="py-3 text-left text-slate-500">ID</th><th class="py-3 text-left text-slate-500">機能名</th><th class="py-3 text-left text-slate-500">概要</th><th class="py-3 text-slate-500">優先度</th></tr></thead><tbody class="text-slate-700"><tr class="border-b border-slate-100"><td class="py-3 font-mono text-indigo-600">FR-001</td><td class="py-3 font-semibold">顧客管理</td><td class="py-3">顧客情報CRUD・検索・一覧出力</td><td class="py-3"><span class="bg-red-100 text-red-700 px-2 py-0.5 rounded text-xs font-bold">必須</span></td></tr><tr class="border-b border-slate-100"><td class="py-3 font-mono text-indigo-600">FR-002</td><td class="py-3 font-semibold">案件管理</td><td class="py-3">案件登録・ステータス管理・パイプライン</td><td class="py-3"><span class="bg-red-100 text-red-700 px-2 py-0.5 rounded text-xs font-bold">必須</span></td></tr><tr class="border-b border-slate-100"><td class="py-3 font-mono text-indigo-600">FR-003</td><td class="py-3 font-semibold">請求管理</td><td class="py-3">請求書発行・入金確認・売上集計</td><td class="py-3"><span class="bg-red-100 text-red-700 px-2 py-0.5 rounded text-xs font-bold">必須</span></td></tr><tr class="border-b border-slate-100"><td class="py-3 font-mono text-indigo-600">FR-004</td><td class="py-3 font-semibold">ダッシュボード</td><td class="py-3">KPI可視化・グラフ・ドリルダウン</td><td class="py-3"><span class="bg-amber-100 text-amber-700 px-2 py-0.5 rounded text-xs font-bold">推奨</span></td></tr><tr class="border-b border-slate-100"><td class="py-3 font-mono text-indigo-600">FR-005</td><td class="py-3 font-semibold">レポート出力</td><td class="py-3">PDF/Excel出力・定期送信</td><td class="py-3"><span class="bg-amber-100 text-amber-700 px-2 py-0.5 rounded text-xs font-bold">推奨</span></td></tr><tr><td class="py-3 font-mono text-indigo-600">FR-006</td><td class="py-3 font-semibold">API連携</td><td class="py-3">外部システム(基幹・Slack・メール)連携</td><td class="py-3"><span class="bg-green-100 text-green-700 px-2 py-0.5 rounded text-xs font-bold">任意</span></td></tr></tbody></table></div>` + TAIL },
    { title: '非機能要件', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">非機能要件</div><div class="grid grid-cols-2 gap-6"><div class="bg-slate-50 rounded-xl p-6"><div class="font-bold text-slate-800 mb-3">性能</div><div class="text-sm text-slate-600">画面応答: 3秒以内 / 同時接続: 100ユーザー / DB検索: 1秒以内</div></div><div class="bg-slate-50 rounded-xl p-6"><div class="font-bold text-slate-800 mb-3">可用性</div><div class="text-sm text-slate-600">稼働率: 99.9% / 計画停止: 月1回2時間以内 / RPO: 1時間 / RTO: 4時間</div></div><div class="bg-slate-50 rounded-xl p-6"><div class="font-bold text-slate-800 mb-3">セキュリティ</div><div class="text-sm text-slate-600">SSL通信必須 / 2FA認証 / ロールベースアクセス制御 / 監査ログ3年保存</div></div><div class="bg-slate-50 rounded-xl p-6"><div class="font-bold text-slate-800 mb-3">移行性・拡張性</div><div class="text-sm text-slate-600">既存データ移行対応 / API拡張可能 / 多言語対応前提 / スケールアウト可能</div></div></div></div>` + TAIL },
  ],
};
