import { docHead, TAIL } from './html-utils.js';
import type { SeedDocument } from './types.js';

export const rfpProposal: SeedDocument = {
  title: 'RFP対応提案書',
  description: 'RFP(提案依頼書)への対応提案書',
  sections: [
    { title: '表紙', html: docHead('<style>body{background:linear-gradient(135deg,#1a1a2e 0%,#16213e 50%,#0f3460 100%);color:#fff}</style>') + `<div class="w-[1920px] h-[1080px] flex flex-col items-center justify-center"><div class="text-7xl font-black mb-6">RFP対応提案書</div><div class="w-32 h-1 bg-amber-400/40 mb-8"></div><div class="text-2xl font-light opacity-80">〇〇システム開発公募に対する提案</div><div class="absolute bottom-16 text-sm opacity-40">CONFIDENTIAL</div></div>` + TAIL },
    { title: '提案概要', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">提案概要</div><div class="grid grid-cols-2 gap-8"><div class="bg-slate-50 rounded-2xl p-8"><div class="text-sm text-slate-500 mb-1">RFP名称</div><div class="text-xl font-bold">〇〇統合業務システム開発</div></div><div class="bg-slate-50 rounded-2xl p-8"><div class="text-sm text-slate-500 mb-1">提案金額</div><div class="text-xl font-bold text-amber-600">1,200万円(税抜)</div></div><div class="bg-slate-50 rounded-2xl p-8"><div class="text-sm text-slate-500 mb-1">提案期間</div><div class="text-xl font-bold">8ヶ月</div></div><div class="bg-slate-50 rounded-2xl p-8"><div class="text-sm text-slate-500 mb-1">対応フェーズ</div><div class="text-xl font-bold">要件定義〜本番運用</div></div></div></div>` + TAIL },
    { title: '対応スケジュール', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">対応スケジュール</div><div class="space-y-4"><div class="flex items-center gap-6"><div class="w-40 text-right font-bold text-slate-600">1-2月</div><div class="flex-1 bg-blue-100 rounded-xl p-4"><div class="font-bold text-blue-800">要件定義</div><div class="text-sm text-blue-600">業務分析・要件整理・基本設計</div></div></div><div class="flex items-center gap-6"><div class="w-40 text-right font-bold text-slate-600">3-4月</div><div class="flex-1 bg-indigo-100 rounded-xl p-4"><div class="font-bold text-indigo-800">詳細設計</div><div class="text-sm text-indigo-600">API設計・DB設計・UI設計</div></div></div><div class="flex items-center gap-6"><div class="w-40 text-right font-bold text-slate-600">5-7月</div><div class="flex-1 bg-purple-100 rounded-xl p-4"><div class="font-bold text-purple-800">開発・テスト</div><div class="text-sm text-purple-600">実装・単体テスト・結合テスト</div></div></div><div class="flex items-center gap-6"><div class="w-40 text-right font-bold text-slate-600">8月</div><div class="flex-1 bg-emerald-100 rounded-xl p-4"><div class="font-bold text-emerald-800">本番移行・運用開始</div><div class="text-sm text-emerald-600">移行作業・教育・運用引継ぎ</div></div></div></div></div>` + TAIL },
    { title: '体制と優位性', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">提案体制と当社の優位性</div><div class="grid grid-cols-2 gap-8"><div><div class="text-lg font-bold text-slate-700 mb-4">プロジェクト体制</div><div class="space-y-3"><div class="bg-slate-50 rounded-lg p-4 flex items-center gap-4"><div class="w-12 h-12 bg-blue-600 rounded-full flex items-center justify-center text-white font-bold">PM</div><div><div class="font-bold">プロジェクトマネージャー</div><div class="text-sm text-slate-500">PMP保有・10年経験</div></div></div><div class="bg-slate-50 rounded-lg p-4 flex items-center gap-4"><div class="w-12 h-12 bg-emerald-600 rounded-full flex items-center justify-center text-white font-bold">SE</div><div><div class="font-bold">シニアエンジニア ×3</div><div class="text-sm text-slate-500">AWS/Next.js/Python専門</div></div></div></div></div><div><div class="text-lg font-bold text-slate-700 mb-4">選ばれる理由</div><div class="space-y-3"><div class="bg-amber-50 rounded-lg p-4"><div class="font-bold text-amber-800">豊富な実績</div><div class="text-sm text-slate-600">同業種での導入実績30社以上</div></div><div class="bg-amber-50 rounded-lg p-4"><div class="font-bold text-amber-800">独自フレームワーク</div><div class="text-sm text-slate-600">開発効率30%UPの独自アセット</div></div></div></div></div></div>` + TAIL },
  ],
};
