import { docHead, TAIL } from './html-utils.js';
import type { SeedDocument } from './types.js';
export const roiCalc: SeedDocument = {
  title: 'ROI試算書',
  description: 'IT投資のROI試算書',
  sections: [
    { title: '表紙', html: docHead('<style>body{background:linear-gradient(135deg,#064e3b 0%,#047857 50%,#059669 100%);color:#fff}</style>') + `<div class="w-[1920px] h-[1080px] flex flex-col items-center justify-center"><div class="text-7xl font-black mb-6">ROI試算書</div><div class="w-32 h-1 bg-white/30 mb-8"></div><div class="text-2xl opacity-80">〇〇システム導入投資対効果</div></div>` + TAIL },
    { title: '投資額', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">投資額(コスト)</div><div class="grid grid-cols-3 gap-6 mb-8"><div class="bg-emerald-50 rounded-2xl p-8 text-center"><div class="text-sm text-emerald-600 mb-2">初期投資</div><div class="text-4xl font-black text-emerald-700">1,200</div><div class="text-sm text-slate-500">万円</div></div><div class="bg-amber-50 rounded-2xl p-8 text-center"><div class="text-sm text-amber-600 mb-2">年間運用費</div><div class="text-4xl font-black text-amber-700">360</div><div class="text-sm text-slate-500">万円/年</div></div><div class="bg-blue-50 rounded-2xl p-8 text-center"><div class="text-sm text-blue-600 mb-2">3年総額</div><div class="text-4xl font-black text-blue-700">2,280</div><div class="text-sm text-slate-500">万円</div></div></div><table class="w-full"><thead><tr class="border-b-2 border-slate-200"><th class="py-3 text-left text-sm text-slate-500">項目</th><th class="py-3 text-right text-sm text-slate-500">金額</th></tr></thead><tbody class="text-slate-700"><tr class="border-b border-slate-100"><td class="py-3">開発費</td><td class="py-3 text-right font-mono">1,200万円</td></tr><tr class="border-b border-slate-100"><td class="py-3">サーバー・インフラ(年)</td><td class="py-3 text-right font-mono">180万円</td></tr><tr class="border-b border-slate-100"><td class="py-3">保守運用(年)</td><td class="py-3 text-right font-mono">180万円</td></tr></tbody></table></div>` + TAIL },
    { title: '効果試算', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">効果試算(ベネフィット)</div><div class="grid grid-cols-2 gap-6 mb-8"><div class="bg-emerald-50 rounded-xl p-6"><div class="font-bold text-emerald-800 mb-2">業務効率化による削減</div><div class="text-sm text-slate-600">月間200時間の作業削減 × 単価5,000円 = 年間1,200万円</div></div><div class="bg-emerald-50 rounded-xl p-6"><div class="font-bold text-emerald-800 mb-2">売上増加</div><div class="text-sm text-slate-600">顧客対応の迅速化により新規獲得+15% = 年間600万円</div></div><div class="bg-emerald-50 rounded-xl p-6"><div class="font-bold text-emerald-800 mb-2">エラー削減</div><div class="text-sm text-slate-600">手作業ミスの削減による損失防止 = 年間240万円</div></div><div class="bg-emerald-50 rounded-xl p-6"><div class="font-bold text-emerald-800 mb-2">意思決定の迅速化</div><div class="text-sm text-slate-600">リアルタイムダッシュボードによる機会損失防止 = 年間360万円</div></div></div><div class="bg-emerald-100 rounded-xl p-6 text-center"><div class="text-sm text-emerald-600 mb-1">年間ベネフィット</div><div class="text-4xl font-black text-emerald-800">2,400万円</div></div></div>` + TAIL },
    { title: '3年間キャッシュフロー', html: docHead() + `<div class="w-[1920px] h-[1080px] bg-white p-20"><div class="text-4xl font-bold text-slate-800 mb-10">3年間キャッシュフロー</div><table class="w-full"><thead><tr class="border-b-2 border-slate-200"><th class="py-3 text-left text-sm text-slate-500">項目</th><th class="py-3 text-right text-sm text-slate-500">1年目</th><th class="py-3 text-right text-sm text-slate-500">2年目</th><th class="py-3 text-right text-sm text-slate-500">3年目</th><th class="py-3 text-right text-sm text-slate-500">累計</th></tr></thead><tbody class="text-slate-700"><tr class="border-b border-slate-100"><td class="py-3 font-semibold">投資額</td><td class="py-3 text-right font-mono text-red-600">-1,560万</td><td class="py-3 text-right font-mono text-red-600">-360万</td><td class="py-3 text-right font-mono text-red-600">-360万</td><td class="py-3 text-right font-mono text-red-600">-2,280万</td></tr><tr class="border-b border-slate-100"><td class="py-3 font-semibold">ベネフィット</td><td class="py-3 text-right font-mono text-emerald-600">+1,800万</td><td class="py-3 text-right font-mono text-emerald-600">+2,400万</td><td class="py-3 text-right font-mono text-emerald-600">+2,400万</td><td class="py-3 text-right font-mono text-emerald-600">+6,600万</td></tr><tr class="border-b border-slate-200 bg-emerald-50"><td class="py-3 font-bold">純効果</td><td class="py-3 text-right font-mono font-bold">+240万</td><td class="py-3 text-right font-mono font-bold">+2,040万</td><td class="py-3 text-right font-mono font-bold">+2,040万</td><td class="py-3 text-right font-mono font-black text-emerald-700 text-lg">+4,320万</td></tr></tbody></table><div class="mt-8 grid grid-cols-3 gap-6"><div class="bg-emerald-50 rounded-xl p-6 text-center"><div class="text-sm text-emerald-600 mb-1">ROI(3年)</div><div class="text-3xl font-black text-emerald-700">190%</div></div><div class="bg-emerald-50 rounded-xl p-6 text-center"><div class="text-sm text-emerald-600 mb-1">投資回収期間</div><div class="text-3xl font-black text-emerald-700">11ヶ月</div></div><div class="bg-emerald-50 rounded-xl p-6 text-center"><div class="text-sm text-emerald-600 mb-1">NPV(割引率5%)</div><div class="text-3xl font-black text-emerald-700">3,810万</div></div></div></div>` + TAIL },
  ],
};
